MOCK_CASE = {
    "case_id": "CASE-001",
    "title": "Ravi Kumar vs ABC Constructions",
    "matter_type": "Property Dispute",
    "jurisdiction": "Bengaluru",
    "client": "Ravi Kumar",
    "opposing_party": "ABC Constructions",
    "summary": "Dispute concerning delayed possession, disputed payments, and alleged threats.",
}

MOCK_UTTERANCES = [
    {
        "utterance_id": "UTT-001",
        "recording_id": "CALL-001",
        "speaker": "Lawyer",
        "start_time": 0.0,
        "end_time": 7.8,
        "text": "Please explain when you first entered into the agreement with ABC Constructions.",
    },
    {
        "utterance_id": "UTT-002",
        "recording_id": "CALL-001",
        "speaker": "Client",
        "start_time": 7.8,
        "end_time": 23.4,
        "text": "I signed the apartment agreement on 14 November 2025. They promised possession by 31 March 2026.",
    },
    {
        "utterance_id": "UTT-003",
        "recording_id": "CALL-001",
        "speaker": "Lawyer",
        "start_time": 23.4,
        "end_time": 28.0,
        "text": "How much money did you pay?",
    },
    {
        "utterance_id": "UTT-004",
        "recording_id": "CALL-001",
        "speaker": "Client",
        "start_time": 28.0,
        "end_time": 45.6,
        "text": "I paid 5 lakh rupees in cash on 2 December 2025 to Ramesh, their sales manager, near the registrar office. Mahesh was present.",
    },
    {
        "utterance_id": "UTT-005",
        "recording_id": "CALL-001",
        "speaker": "Client",
        "start_time": 45.6,
        "end_time": 60.2,
        "text": "Later, on 18 June 2026, Ramesh called and threatened me when I asked for the refund.",
    },
    {
        "utterance_id": "UTT-006",
        "recording_id": "CALL-002",
        "speaker": "Lawyer",
        "start_time": 0.0,
        "end_time": 8.5,
        "text": "You previously said the payment was made in cash. Is that correct?",
    },
    {
        "utterance_id": "UTT-007",
        "recording_id": "CALL-002",
        "speaker": "Client",
        "start_time": 8.5,
        "end_time": 24.9,
        "text": "Actually, I transferred 4 lakh rupees on 5 December 2025. I may have confused it with another payment.",
    },
    {
        "utterance_id": "UTT-008",
        "recording_id": "CALL-002",
        "speaker": "Client",
        "start_time": 24.9,
        "end_time": 37.1,
        "text": "The threat may have happened on 19 June, not 18 June. I need to check my call log.",
    },
]

MOCK_ENTITIES = [
    {"entity_id": "ENT-001", "name": "Ravi Kumar", "type": "PERSON", "roles": ["Client"]},
    {"entity_id": "ENT-002", "name": "ABC Constructions", "type": "ORGANIZATION", "roles": ["Opposing Party"]},
    {"entity_id": "ENT-003", "name": "Ramesh", "type": "PERSON", "roles": ["Sales Manager", "Alleged Recipient"]},
    {"entity_id": "ENT-004", "name": "Mahesh", "type": "PERSON", "roles": ["Possible Witness"]},
    {"entity_id": "ENT-005", "name": "Registrar Office", "type": "LOCATION", "roles": ["Alleged Payment Location"]},
]

MOCK_CLAIMS = [
    {
        "claim_id": "CLM-001",
        "category": "AGREEMENT",
        "statement": "The client signed an apartment agreement on 14 November 2025.",
        "status": "ALLEGED",
        "source_utterances": ["UTT-002"],
        "confidence": 0.96,
    },
    {
        "claim_id": "CLM-002",
        "category": "PROMISE",
        "statement": "ABC Constructions promised possession by 31 March 2026.",
        "status": "ALLEGED",
        "source_utterances": ["UTT-002"],
        "confidence": 0.95,
    },
    {
        "claim_id": "CLM-003",
        "category": "PAYMENT",
        "statement": "The client paid ₹5 lakh in cash on 2 December 2025 to Ramesh.",
        "status": "DISPUTED",
        "source_utterances": ["UTT-004"],
        "confidence": 0.91,
    },
    {
        "claim_id": "CLM-004",
        "category": "PAYMENT",
        "statement": "The client transferred ₹4 lakh on 5 December 2025.",
        "status": "DISPUTED",
        "source_utterances": ["UTT-007"],
        "confidence": 0.89,
    },
    {
        "claim_id": "CLM-005",
        "category": "THREAT",
        "statement": "Ramesh threatened the client after a refund request around 18 or 19 June 2026.",
        "status": "ALLEGED",
        "source_utterances": ["UTT-005", "UTT-008"],
        "confidence": 0.78,
    },
]

MOCK_TIMELINE = [
    {
        "event_id": "EVT-001",
        "date": "2025-11-14",
        "date_precision": "EXACT",
        "event_type": "AGREEMENT_SIGNED",
        "description": "Client allegedly signed an apartment agreement with ABC Constructions.",
        "source_utterances": ["UTT-002"],
    },
    {
        "event_id": "EVT-002",
        "date": "2025-12-02",
        "date_precision": "DISPUTED",
        "event_type": "PAYMENT",
        "description": "Client initially stated that ₹5 lakh was paid in cash to Ramesh.",
        "source_utterances": ["UTT-004"],
    },
    {
        "event_id": "EVT-003",
        "date": "2025-12-05",
        "date_precision": "DISPUTED",
        "event_type": "PAYMENT",
        "description": "Client later stated that ₹4 lakh was transferred.",
        "source_utterances": ["UTT-007"],
    },
    {
        "event_id": "EVT-004",
        "date": "2026-03-31",
        "date_precision": "EXACT",
        "event_type": "POSSESSION_DEADLINE",
        "description": "Promised possession deadline.",
        "source_utterances": ["UTT-002"],
    },
    {
        "event_id": "EVT-005",
        "date": "2026-06-18/2026-06-19",
        "date_precision": "CONFLICTING",
        "event_type": "ALLEGED_THREAT",
        "description": "Client alleges that Ramesh threatened him after a refund request.",
        "source_utterances": ["UTT-005", "UTT-008"],
    },
]

MOCK_CONTRADICTIONS = [
    {
        "contradiction_id": "CON-001",
        "topic": "Payment amount, date, and method",
        "severity": "HIGH",
        "statement_a": "₹5 lakh paid in cash on 2 December 2025.",
        "statement_b": "₹4 lakh transferred on 5 December 2025.",
        "source_a": "UTT-004",
        "source_b": "UTT-007",
        "possible_explanation": "The statements may refer to separate payments, or the client may have recalled the original payment incorrectly.",
        "requires_review": True,
    },
    {
        "contradiction_id": "CON-002",
        "topic": "Date of alleged threat",
        "severity": "MEDIUM",
        "statement_a": "The threat occurred on 18 June 2026.",
        "statement_b": "The threat may have occurred on 19 June 2026.",
        "source_a": "UTT-005",
        "source_b": "UTT-008",
        "possible_explanation": "The call log may resolve the date discrepancy.",
        "requires_review": True,
    },
]
